# 应用服务 WEB 访问端口
server:
  port: 8080

# 数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: "lch"   #云端数据库用户名
    password: "D9:s+zA?m+l.6hp9" #云端数据库密码
    url: jdbc:mysql://123.249.69.64:3306/school?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC

    # 配置mybatis实体和xml映射
    mybatis:
      mapper-locations: classpath:mapper/*.xml
      type-aliases-package: com.example.entity